const animations = [
  'fade-up',
  'fade-down',
  'fade-left',
  'fade-right',
  'fade-up-right',
  'fade-up-left',
  'fade-down-right',
  'fade-down-left',
  'zoom-in',
  'zoom-in-up',
  'zoom-in-down',
  'zoom-in-left',
  'zoom-in-right',
  'zoom-out',
  'zoom-out-up',
  'zoom-out-down',
  'zoom-out-left',
  'zoom-out-right',
  'slide-up',
  'slide-down',
  'slide-right',
  'slide-left',
  'flip-left',
  'flip-right',
  'flip-up',
  'flip-down',
];

export { animations };
